name: cfcr-jumpbox
features:
  use_dns_addresses: true

releases:
- name: kubo
  version: latest
- name: cfcr-jump-box
  version: latest
- name: bosh-dns
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: "3541.10"

addons:
- name: bosh-dns
  include:
    stemcells:
    - os: ubuntu-trusty
  jobs:
  - name: bosh-dns
    release: bosh-dns
    properties:
      cache:
        enabled: true
      health:
        enabled: true
        server:
          tls: ((/dns_healthcheck_server_tls))
        client:
          tls: ((/dns_healthcheck_client_tls))
- name: bosh-dns-aliases
  jobs:
  - name: kubo-dns-aliases
    release: kubo
    consumes:
      kube-apiserver: {from: master, deployment: cfcr}
      etcd: {from: etcd, deployment: cfcr}

instance_groups:
- name: jumpbox
  instances: 1
  networks:
  - name: default
  azs: [z1,z2,z3]
  jobs:
    - name: kubectl
      release: cfcr-jump-box
      consumes:
        kube-apiserver: {from: master, deployment: cfcr}
  stemcell: trusty
  vm_type: small

update:
  canaries: 3
  max_in_flight: 3
  canary_watch_time: 10000-300000
  update_watch_time: 10000-300000

